### ISSUE TITLE
bug: [ERROR] Invalid project type: react-vite

### ISSUE THREAD

**Issue by jonz94** [ionic-team/vscode-extension#101]
### Ionic Framework Version

v7.x

### Current Behavior

After creating a new ionic react v7 project, I cannot run the project via vscode extension.

When click the `Run > Web` button on the vscode extension sidebar menu, the following error will occur:

```
[Ionic] Running on Web...
> npx ionic serve --external
[ERROR] Invalid project type: react-vite (project config: .\ionic.config.json).
        
        Project type must be one of: angular, react, vue, ionic-angular, ionic1, custom
Bad project type: undefined
[error] node "c:\Users\jonz94\.vscode\extensions\ionic.ionic-1.34.1\node_modules\@ionic\cli\bin\ionic" serve --external Failed
[error] Web Failed.
```

![image](https://user-images.githubusercontent.com/16042676/230088023-f5863f8a-d043-4862-90b8-720de96d6726.png)

### Expected Behavior

After click the `Run > Web` button, the project should be able to run without errors.

In addition, if we manually type `ionic serve --external` command in the terminal, it works as expected without any issues.

![image](https://user-images.githubusercontent.com/16042676/230089671-928eef55-7e74-4b42-92b1-cd49ad78535f.png)

So I believe the issue might be related to the vscode extension.

### Steps to Reproduce

1. `npx @ionic/cli@latest start i7-react tabs --type=react`
2. `cd i7-react`
3. `code .`
4. Click `Run > Web` button on the vscode extension sidebar menu.

### Ionic Info

Ionic:

   Ionic CLI       : 7.0.0 (C:\Users\jonz94\AppData\Local\npm-cache\_npx\60a35572691ec3be\node_modules\@ionic\cli)
   Ionic Framework : @ionic/react 7.0.0

Capacitor:

   Capacitor CLI      : 4.7.3
   @capacitor/android : not installed
   @capacitor/core    : 4.7.3
   @capacitor/ios     : not installed

Utility:

   cordova-res : not installed globally
   native-run  : 1.7.2

System:

   NodeJS : v18.15.0 (C:\Users\jonz94\AppData\Local\fnm_multishells\1828_1680697361600\node.exe)
   npm    : 9.6.2
   OS     : Windows 10

**Comment by dtarnawsky** [comment]
Hey @jonz94,

Just waiting on a release of the Ionic CLI v7 that fixes the ionic login command and we can update the extension. Hopefully this happens today....

**Comment by dtarnawsky** [comment]
Hey @jonz94,

This is now fixed in the extension version 1.34.2 released just now. If you also have version 7.0.0 of Ionic CLI installed globally I would suggest updating to 7.0.1.

**Comment by jonz94** [comment]
Hi @dtarnawsky, thanks for the quick response and the fix!

I can confirm this issue has been fixed in the latest version! (extension 1.34.2 + Ionic CLI 7.0.1)

![image](https://user-images.githubusercontent.com/16042676/230264526-e8cbe9a0-c8f1-447b-b6f9-59b85386c1bd.png)

**Comment by ronaldsbraivo** [comment]
Seems that this issue is still present for vue projects using vite!
<img width="1440" alt="Screenshot 2023-04-13 at 20 09 04" src="https://user-images.githubusercontent.com/25848436/231834167-6c0d105a-c314-4446-8f7d-516c0befdb39.png">
<img width="1440" alt="Screenshot 2023-04-13 at 20 07 57" src="https://user-images.githubusercontent.com/25848436/231834181-af706e0a-6552-4173-9cc8-f842fa0751d5.png">

**Comment by dj-fiorex** [comment]
Hello guys, sorry to reopen this, but i have the same exact problem with the latest version of the extension 1.34.0.
Fresh react-vite project, template Menu, then add Android project then select run on Android
this is the error:
```
[Ionic] Google sdk_gphone64_arm64 Android 13...
> export ANDROID_HOME=~/Library/Android/sdk && npx ionic build && npx cap copy android && npx cap run android --target=emulator-5554  --external --no-build --no-sync
[ERROR] Invalid project type: react-vite (project config: ./ionic.config.json).
        
        Project type must be one of: angular, ionic-angular, ionic1, custom, react, vue
Bad project type: undefined
[error] export ANDROID_HOME=~/Library/Android/sdk && npx ionic build && npx cap copy android && npx cap run android --target=emulator-5554  --external --no-build --no-sync Failed
[error] Android Failed.

```
i don't have ionic nor capacitor globally installed
Can someone help me?


EDIT:
if i try to run the command directly forcing npx to use the latest version of the ionic cli i receive the same error:
```
export ANDROID_HOME=~/Library/Android/sdk && npx ionic@latest build && npx cap copy android && npx cap run android --target=emulator-5554  --external --no-build --no-sync
Need to install the following packages:
  ionic@latest
Ok to proceed? (y) 
npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated superagent@4.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
npm WARN deprecated ionic@5.4.16: The Ionic CLI now uses ✨ @ionic/cli ✨ for its package name! 👉 https://twitter.com/ionicframework/status/1223268498362851330
[ERROR] Invalid project type: react-vite (project config: ./ionic.config.json).
        
        Project type must be one of: angular, ionic-angular, ionic1, custom, react, vue

Bad project type: undefined
```

**Comment by jonz94** [comment]
> EDIT: if i try to run the command directly forcing npx to use the latest version of the ionic cli i receive the same error:
> 
> ```
> export ANDROID_HOME=~/Library/Android/sdk && npx ionic@latest build && npx cap copy android && npx cap run android --target=emulator-5554  --external --no-build --no-sync
> Need to install the following packages:
>   ionic@latest
> Ok to proceed? (y) 
> npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
> npm WARN deprecated superagent@4.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
> npm WARN deprecated ionic@5.4.16: The Ionic CLI now uses ✨ @ionic/cli ✨ for its package name! 👉 https://twitter.com/ionicframework/status/1223268498362851330
> [ERROR] Invalid project type: react-vite (project config: ./ionic.config.json).
>         
>         Project type must be one of: angular, ionic-angular, ionic1, custom, react, vue
> 
> Bad project type: undefined
> ```

If you look closely:

npm WARN deprecated ionic@5.4.16: The Ionic CLI now uses ✨ @ionic/cli ✨ for its package name! 👉 https://twitter.com/ionicframework/status/1223268498362851330

So, I think replace `ionic` with `@ionic/cli` should be able to solve the issue on your end.

```
export ANDROID_HOME=~/Library/Android/sdk && npx @ionic/cli@latest build && npx cap copy android && npx cap run android --target=emulator-5554 --external --no-build --no-sync
```

**Comment by dtarnawsky** [comment]
Hey @jonz94,

Can you please remove the old version of ionic (the deprecated version 5.4.16):
`npm uninstall ionic -g`

And then install a supported version with:
`npm install -g @ionic/cli`
