### ISSUE TITLE
npm outdated is being called with a project that uses pnpm 

### ISSUE THREAD

**Issue by dtarnawsky** [ionic-team/vscode-extension#121]

**Comment by dtarnawsky** [comment]
This issue has been resolved in v1.45.4 where pnpm outdated and pnpm list are now being used when pnpm is used as the package manager.

**Comment by oweitman** [comment]
In Version 1.48.0 the error still/again exists
if i downgrade to 1.45.4 the error is gone
please reopen

`[error] Unable to run 'npm outdated --json'. Try reinstalling node modules.`

**Comment by dtarnawsky** [comment]
Hey @oweitman, I'm having a hard time reproducing an issue with 1.48.0. Are you able to supply a sample project with the problem? (you can send to damian at ionic.io)

**Comment by oweitman** [comment]
hi,

yes it is easy:
- create new project with ionic start with following settings
no wizard, vue, project name test, starter template tabs
- after installtion is complete
- reopen vscode with new generated folder "test"
- if vscode is open, go to the ionic-extension
- in output window there is:

[error] Unable to run 'npm outdated --json'. Try reinstalling node modules.

this error is repeated everytime i select a different command in the ionic extension

versions: 
vscode
Version: 1.80.2 (user setup)
Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Date: 2023-07-27T20:40:28.909Z
Electron: 22.3.14
ElectronBuildId: 22695494
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

ionic extension: v1.48.0

if you need more informations, please comment
if i should upload the sources to github, no problem,
but the source are unchanged from your scaffolding process

**Comment by dtarnawsky** [comment]
Thanks, can you run` ionic -v` and see what version of the Ionic CLI you are using?

Also, if you try this by creating the project with the VS Code extension does it work?

**Comment by oweitman** [comment]
ionic CLI is 7.1.1

if i try the extension wizard to create a project, i noticed other problems
- the wizard didnt use the directory that i opened for vscode
- if i want to select a different directory, then a message/toast is shown
"File system provider for C:%5CUsers%5Cmsowa is not available."
and i cant select a different directory
- the name of the created directory is not test1, it is 'test1' (with the ‘ Char)
- after i changed the directory with vscode and open the ionic extension again there is the message
[error] Unable to run 'npm outdated --json'. Try reinstalling node modules.

**Comment by dtarnawsky** [comment]
Hi @oweitman, just an FYI: version 1.49.0 is out and fixes the errors related to creating a new project on a Window machine. 

I saw that you have https://github.com/ionic-team/vscode-extension/issues/129 open, and i'll use that to see if there is a fix related to your test steps.

**Comment by danbaechtold** [comment]
I (still) have the same error.

My setup is as follows: I'm using PNPM and the Capacitor app is in a subfolder "/app", with it's own package.json and pnpm-lock.yaml file.

The Ionic Extension correctly discovers the subfolders as projects, but still tries to use NPM instead of PNPM.

**Comment by dtarnawsky** [comment]
Hi @danbaechtold, are you able to provide a sample reproduction of a project with the problem? Also, does the root folder contain a package-lock.json file which may cause the extension to think you are using npm?

**Comment by danbaechtold** [comment]
Hi @dtarnawsky,

No, the root folder does not contain a package-lock.json.

Unfortunately it's a client's project, so I can't, but it's simple to reproduce:
1. Use VSCode and the Extension to create a new project (I've chosen with Vue)
2. Close VSCode, delete package-lock.json and node_modules
3. Move all the files and folders to a subfolder, for example "app" (except .git, .vscode folders)
4. Reopen VSCode; Make sure PNPM is the default package manager to execute scripts (search for "Npm: Package Manager" in Settings)
5. Run pnpm install
6. Open the the Ionic Extension

The error will then appear in the extension's output/console:
`[error] Unable to run 'npm outdated --json'. Try reinstalling node modules.`

**Comment by dtarnawsky** [comment]
Thanks for details @danbaechtold , this issue is now fixed in version 1.55 released today. You would normally setup pnpm with workspaces to do this but now the extension also understands if you are just using a folder based structure with subfolders that are pnpm based.

**Comment by danbaechtold** [comment]
@dtarnawsky Awesome thank, works! :)
